spring:
  application:
    name: guardrail-service

# Logging
logging:
  level:
    root: INFO
    com.vanguard.guardrail: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"

# Server
server:
  port: 8083
